baseURL = "https://pgrunm.github.io/"
languageCode = "en-us"
title = "System Engineering Blog"

# Name of the theme.
# Documentation of the theme: https://github.com/luizdepra/hugo-coder/wiki
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

[params]
    author = "Pascal Grundmeier"
    info = "System Engineer"
    description = "Pascal Grundmeiers's personal website"
    keywords = "blog,devops engineer, site reliability engineer"
    avatarurl = "images/avatar.png"

    favicon_32 = "/img/favicon-32x32.png"

    footercontent = "Welcome to my website. Feel free to contact me or read one of my blog posts."

    colorscheme = "auto"

    since = 2019

    rtl = false

    math = true

# Social links, see docs here: https://forkaweso.me/Fork-Awesome/icons/
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/pgrunm/"
[[params.social]]
    name = "E-Mail"
    icon = "fa fa-envelope fa-2x"
    weight = 2
    url = "https://mailhide.io/e/kQhcqCgM"
[[params.social]]
    name = "Telegram"
    icon = "fa fa-telegram fa-2x"
    weight = 3
    url = "https://t.me/Pascal982"
[[params.social]]
    name = "Xing"
    icon = "fa fa-xing  fa-2x"
    weight = 4
    url = "https://www.xing.com/profile/Pascal_Grundmeier"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss fa-2x"
    weight = 5
    url = "https://pgrunm.github.io/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

# Menu links
[[menu.main]]
    name = "Home"
    weight = 1
    url  = "/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "About Me"
    weight = 3
    url = "/about/"
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "/contact/"
[[menu.main]]
    name = "RSS"
    weight = 5
    url = "/index.xml"