baseURL = "http://example.org/"
languageCode = "en-us"
title = "Pascal Grundmeier"

# Name of the theme.
# Documentation of the theme: https://github.com/luizdepra/hugo-coder/wiki
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Pascal Grundmeier"
    info = "System Engineer Windows & Linux"
    description = "Pascal Grundmeiers's personal website"
    keywords = "blog,devops engineer, site reliability engineer"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Welcome to my website."

    colorscheme = "auto"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links, see docs here: https://fontawesome.com/icons?d=gallery&m=free
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/pgrunm/"
[[params.social]]
    name = "E-Mail"
    icon = "fa fa-envelope fa-2x"
    weight = 2
    url = "mailto:test@example.com"
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram-plane fa-2x"
    weight = 3
    url = "https://t.me/Pascal982"
[[params.social]]
    name = "Xing"
    icon = "fab fa-xing  fa-2x"
    weight = 4
    url = "https://xing.com/pascal.grundmeier/"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 5
    url = "https://pgrunm.github.io/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

# Menu links
[[menu.main]]
    name = "Home"
    weight = 1
    url  = "/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "contact/"